#!/usr/bin/python3
# -*- coding: utf-8 -*-

import sys
import time
import random
from PyQt5.QtWidgets import QApplication, QWidget



if __name__ == '__main__':

    app = QApplication(sys.argv)

    w = QWidget()
    w.resize(450, 350)
    w.move(300, 300)
    w.setWindowTitle('Закрой меня')
    w.show()
    while(True):
        time.sleep(0.5)        
        w.move(random.randrange(1000), random.randrange(1000))

    
    sys.exit(app.exec_())
